services:
  mysql1:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jerry
    ports:
      - "3307:3306"
  mysql2:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pikachu
    ports:
      - "3308:3306"
